namespace:
  name: demo-namespace
  labels:
    environment: dev
    team: platform

networkPolicy:
  enabled: true
  name: default-deny
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress: []
